apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: echo-server
  name: echo-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: echo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo-server
    spec:
      containers:
      - image: ealen/echo-server
        name: ehco-server
        ports:
        - containerPort: 8080
